[package]
name = "neots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
text_io = "0.1.12"
rpassword = "0.0.4"
chacha20poly1305 = "0.10.1"
